" Disable compatibility with vi
set nocompatible

" Tabs
set tabstop=4
set shiftwidth=4

" Syntax highlighting
syntax enable

" Enable plugin support
filetype plugin on

" Enable search path for files
set path+=**

" Tab-complition all matches
set wildmenu

" FILE BROWSING:
" Disable banner
let g:netrw_banner=0

" Open in prior window
let g:netrw_browse_split=4

" Open splits to the right
let g:netrw_altv=1

" Tree view
let g:netrw_liststyle=3

" Spellchecking
map <F6> :setlocal spell! spelllang=en_us<CR>
" Spellcheck for git commit
autocmd Filetype gitcommit setlocal spell textwidth=72

" Enable hybrid line numbers
set number relativenumber

" Go
let g:go_def_mode='gopls'
